// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzovqquspssnegxauhmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6b3ZxcXVzcHNzbmVneGF1aG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjUzOTksImV4cCI6MjA2NTc0MTM5OX0.PmXnA5_KD1P_CXGmoIUJF2uU5BpjlUgqhibeBPRvhmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);